spring.application.name=Tenzies_Backend
spring.data.mongodb.uri=mongodb+srv://spidy_amar:Amarthya_2156@cluster0.vkcf6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=Amar
